### PR TITLE
Change 'Active' into 'Runtime'

### PR DESCRIPTION
**Pull request by ThomasSRL**
Change active into runtime, since paused miners can hardly be called active :p
Another option might be 'Time Active'?

### CODE REVIEW

**Comment by lee-aaron** [comment]
Sounds good

**Comment by fonyo** [comment]
I get your point, however, I am not a fan of using naming conventions that are not user-friendly or had to be thought through by the user. If you just think of the thousands of users not knowing what to do with their rigs after Nicehash is gone, we need simple(r) things everywhere! Using the word "runtime" instead of an easily understandable word such as "active" goes against future plans to simplify MPM so that users with very limited technical knowledge could still get it straight away without thinking. The less IT jargon, the better.

**Comment by ThomasSRL** [comment]
Fonyo, then change it into 'Time active'?

Because currently it says 'Active' even for the scripts that are paused or that have failed.
That is counterintuitive, Active should mean running or mining currently., while it is the header for the column about a time quantity, not a boolean.

**Comment by aaronsace** [comment]
@ThomasSRL It's obvious that it's a time and don't think the term active is confusing. 

What about the term Uptime? 
https://en.wikipedia.org/wiki/Uptime

**Comment by fonyo** [comment]
The 'Time Active' suggestion is still the best if the label 'Active' is needed to be changed.

**Comment by aaronsace** [comment]
Going to close this; had many people get confused by lots of things but nobody has ever got confused by this.

**Comment by fonyo** [comment]
@aaronsace @ThomasSRL @lee-aaron @UselessGuru 
Someone posted a youtube video on setting up MPM with MPH. It is very comprehensive and there was a comment from someone asking for a video to be posted on how to cash out on MPH. This is the world we live in... Keep it stupidly simple.
https://www.youtube.com/watch?v=GusEhCDBha4

**Pull request closed without merging**
