### PR TITLE
Add Windows 8 to powershell requirments

### PR DESCRIPTION
**Pull request by dpsi**
Windows 8 doesn't have the updated version of powershell either

### CODE REVIEW

**Comment by fonyo** [comment]
What about Windows 8.1?

**Comment by dpsi** [comment]
Yes, 8.1 as well. Most consider the 2 the same at this point.

**Comment by fonyo** [comment]
Well, there is a huge difference between the two. The users who did not update to 8.1 at all...

**Comment by dpsi** [comment]
8 comes with ps 3, 8.1 has ps 4, just confirmed on 2 vm templates I had.

**Pull request merged**
