### PR TITLE
Update PhoenixMiner to 2.9e

### PR DESCRIPTION
**Pull request by Rama-Nujan**
The original files were renamed in place to keep both. 2.9e has some stability issued with Maxwell cards - thus the 2.8c version should remain. Some have reported no hashrate difference on some cards.

I don't own AMD cards - so I went with the modification by intuition. I have not tested this on AMD cards.

### CODE REVIEW

**Comment by Rama-Nujan** [comment]
Tried to revert the commit and separate individually, but I cant "commit" a file deletion I think. Only admins maybe?

**Comment by Rama-Nujan** [comment]
Good to know. I'll do that

**Comment by grantemsley** [comment]
Also please do not link to copies of miners on your own github repos (unless you're the actual author of course).

Either link to the official release on the author's github/site, or if there isn't one, link to their release page and we will get the miner from there and upload to the MultiPoolMiner miner-binaries repo.

That's the best way we can ensure the links don't get broken or replaced with malicious ones from someone's github account getting hacked.

**Comment by Rama-Nujan** [comment]
Will do - I used my own git because this is only available on bct.

**Comment by grantemsley** [comment]
@Rama-Nujan yeah, get that.  I'd just rather that if we have to point to our own copy, it be one under the MPM team - that way we can make sure it's updated properly even if you move on to other things, and one less way it could get hacked.

**Comment by Rama-Nujan** [comment]
Thank you!!

**Comment by Rama-Nujan** [comment]
> Link to official sources please
Done for 2.9e, reverted for 2.8c which is not in mpm-binaries yet

**Comment by Rama-Nujan** [comment]
The requested changes are done - this can be pulled in

**Comment by grantemsley** [comment]
Master is already using 2.9e as of https://github.com/MultiPoolMiner/MultiPoolMiner/commit/ac2c6553805f534f9e62b1367de071b26aac8625#diff-f0c33c2b6e1c9b66cf421e313cd92a6c, so this PR doesn't really do anything but add a duplicate.  Sorry for the confusion.

If it's actually worthwhile, we could add 2.8 back in.  I haven't seen any issues with 2.9, but I don't have any 900 series Nvidia cards in use.  I don't know that it's actually worth it though.

**Pull request closed without merging**
