### PR TITLE
Timestamp correction for logs

### PR DESCRIPTION
**Pull request by Ondalf**

### CODE REVIEW

**Comment by aaronsace** [comment]
I prefer the simpler output. I think it was just as simple putting lower case hour instead of upper. 

Does this work for you: ".\Logs\$(Get-Date -Format "yyyy-MM-dd_HH-mm-ss").txt"

**Comment by Ondalf** [comment]
Yes it did, but I thought that -Format o is just a bit more universal. Even some kind of a standard. Used that actually for a while, but removed it afterwards I found one that fits for all (aka ignores barriers caused by international settings).

**Comment by aaronsace** [comment]
True, I had considered it previously but as you have to manipulate it then it's no longer a standard. In the end, I just wanted a file name that was unique and made sense.

**Comment by Ondalf** [comment]
Yeah, filesystem sets limits here. I might as well revert it. Well, consider it as solved.

**Pull request closed without merging**
