### PR TITLE
Add Algos

### PR DESCRIPTION
**Pull request by snakethejake81**
Added and consolidated Ccminer algos.

### CODE REVIEW

**Comment by aaronsace** [comment]
Sorry, it's already in 'Get-Algorithm' so just remove it from ccminer.

**Comment by Ondalf** [comment]
For reason X, this is the only way it works for now. MyriadGroestl for MPH and MyrGr for zpool. That dash in the API request causes "a bit" trouble. Even if it's in the Get-Algorithm.

**Comment by snakethejake81** [comment]
Removing MyrGr from ccminer removes it completely when processing zpool.  Zpool lists is as myr-gr which Get-Algorithm reduces to MyrGr, but without it being in the ccminer files it doesn't bring it up.

**Comment by aaronsace** [comment]
I've now fixed the function. :)

**Pull request merged**
