### PR TITLE
3 miner mods

### PR DESCRIPTION
**Pull request by scaras**
ccminer palgin (32 and 64bit)
ccminer 2.2 mod r1 (djm34 and ...)
ccminer 2.2 mod r2 (with cuda 9 build)

in the speeds.txt you see the combined speeds for one gtx 1080 and gtx 1050 ti with a nice OC (and 1080 watercooled)
[speeds.txt](https://github.com/aaronsace/MultiPoolMiner/files/1236992/speeds.txt)

### CODE REVIEW

**Comment by aaronsace** [comment]
That's a lot miners. Are they faster at certain algorithms? 

The algorithm lists on them new filtering down otherwise there will be too many.

**Comment by scaras** [comment]
the speeds.txt shows all algo's compaired with tpruvot 2.2 32 and 64 bit

**Comment by aaronsace** [comment]
Ah, I get it now. Thanks!

**Comment by aaronsace** [comment]
I've merged but will comment out a lot of the algorithms. Some nice speed improvements.

**Comment by scaras** [comment]
i just finniched my own benchmarks and also gonne take the faster ones (the palginx64 qubit and x11 algo are faster but way less shares

**Comment by aaronsace** [comment]
How come this is so much faster with skunk: 
https://github.com/scaras/ccminer-2.2-mod-r1/releases/download/2.2-r1/2.2-mod-r1.zip

**Pull request merged**
