### PR TITLE
Add YiiMP Pool & NVIDIA Stats

### PR DESCRIPTION
**Pull request by jakewarren81**

### CODE REVIEW

**Comment by snakethejake81** [comment]
yiimp.ps1 requires adding individual coin wallets directly to the file.  Not sure the best way to handle this with the rest of the script so I isolated it there for now.

NVIDIA stats depends on nvidia-smi.exe being present which is installed with the drivers.  It only runs it if NVIDIA type is selected.

**Comment by aaronsace** [comment]
Looks great but I'm not going to merge this at the moment.

**Comment by aaronsace** [comment]
Can you clarify as to what this actually means: 
"No registration is required, we do payouts in the currency you mine. Use your wallet address as the username. "

Take 'equihash', do you put a 'Komodo' wallet or a 'Hush' wallet? Does it not matter? Can you just mine any algorithm and coin and set the payout to 'LBC'?

**Comment by snakethejake81** [comment]
So YiiMP doesn't do auto-switching or auto-exchanging like zpool does, even though its using the same back end.  Think of it as a normal pool with a bunch of coins.  You don't mine algo's, you mine specific coins.  It will auto detect which coin wallet you put in and mine for that coin's wallet.  It doesn't auto-exchange.  

You get paid in the coins you mine.  So if you mine komodo, you get paid in komodo.  So I entered wallets from various exchanges and it mines to those wallets when mining the various coins.

**Comment by aaronsace** [comment]
Ah, I see. The profitably API won't be any use then. It could be linked to whattomine and shapeshift.

**Comment by snakethejake81** [comment]
I had the admin add the estimated profit to the currencies API call.  It doesn't show in on the web docs but it's there when you query the API.  That's where I'm pulling the profitability for switching.

Sent from my iPhone

On Jun 14, 2017, at 9:11 AM, aaronsace <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, I see. The profitably API won't be any use then. It could be linked to whattomine and shapeshift.

**Comment by aaronsace** [comment]
Oh, nice. :)

**Comment by aaronsace** [comment]
I'll definitely add this in the next release.

**Comment by jakewarren81** [comment]
Need to update since there have been a lot of changes to master.

**Pull request closed without merging**
